### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by anissen** [josuigoa/gesluxe#5]
It would be nice with some basic documentation about the library or a how-to guide. How to initialise the library, listen to events and handle gesture events. 

For instance, something like the following:

```haxe
        // ...

        Gesluxe.init();

        zoomGesture = new ZoomGesture();
        zoomGesture.events.listen(GestureEvent.GESTURE_BEGAN, onZoomGesture);
        zoomGesture.events.listen(GestureEvent.GESTURE_CHANGED, onZoomGesture);
    }

    function onZoomGesture(event: GestureEventData) {
        Luxe.camera.scale.set_xy(zoomGesture.scaleX, zoomGesture.scaleY);
    }
```

**Comment by josuigoa** [comment]
What o you mean, a general guide in the Readme.md file (like yours in the comment)? Or more detailed documentation about every gesture?

**Comment by anissen** [comment]
I was simply thinking about some example code that shows how to setup and handle the gestures. It's not apparent that e.g. you need to call `Gesluxe.init()` before initializing gestures.

More detailed documentation would also be nice, but some simple "getting started" guide would suffice :)

**Comment by josuigoa** [comment]
Done! I think it would be enough :smile:

**Comment by anissen** [comment]
Thanks :+1:
